name: Security CI

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  prepare:
    name: Prepare environment
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.node.outputs.node-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies (generate lockfile)
        run: |
          # use npm ci if package-lock.json already exists, otherwise npm install
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

  sca-snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json
