name: Security Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    name: Security CI Pipeline

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: SCA - Snyk dependency scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
      
      - name: SAST - Semgrep static analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"

      - name: Secret Scan - Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --verbose